env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - SWIFT_VERSION=2018-10-17
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode10
      before_install:
        - curl -O "https://storage.googleapis.com/swift-tensorflow/mac/swift-tensorflow-DEVELOPMENT-${SWIFT_VERSION}-a-osx.pkg"
        - sudo installer -pkg "swift-tensorflow-DEVELOPMENT-${SWIFT_VERSION}-a-osx.pkg" -target /
        - export PATH="/Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-${SWIFT_VERSION}-a.xctoolchain/usr/bin:${PATH}"
        - pip install lit
      script:
        - make testall
